// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbloapgrczauatzgyboc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibG9hcGdyY3phdWF0emd5Ym9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTQyMDAsImV4cCI6MjA2MDgzMDIwMH0.LKrIHluFGhhSfHe9aAl1sLMpgJLISH4VwZ9lR4ryqFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);